export { default as Dictionary } from './Dictionary'
export { default as Favorites } from './Favorites'
export { default as Register } from './Register'
export { default as Login } from './Login'
export { default as Error } from './Error'